### ISSUE TITLE
no available scaffold

### ISSUE THREAD

**Issue by eddyekofo94** [mardiros/pyramid_asyncio#5]
`pcreate -s aio_jinja2 helloworld`
**Warning:** could not load entry point aio_jinja2 (ImportError: cannot import name 'ViewDeriver')
Unavailable scaffolds: aio_jinja2

python3.6.1 macOSSierra

any idea?

**Comment by mardiros** [comment]
I am almost sure that pyramid_asyncio does not work with pyramid 1.8

This plugin use non public interface so it is not publicly maintainable as is.

The good new, is that in pyramid 1.8, the ViewDeriver is extensible via a zope.interface, so it is possible to clean the code and implement it properly.

I have not try to update it but it could be cool.

**Comment by mardiros** [comment]
Fixe by https://github.com/mardiros/pyramid_asyncio/commit/bde87b3321954bd237cdb760bdbe607b622be418
